### ISSUE TITLE
Multiple problems with mergeing arrays

### ISSUE THREAD

**Issue by gezeta-id** [jesusgm/deepMerge#1]
A couple of _problems_ with your code...

----

First: Your tests are now passing _only because they contain an error_.

On [line 46 of your tests](https://github.com/jesusgm/deepmergefn/blob/cae1a39319abbb67aba291ff0bb1f5a7e0ddc901/index.test.js#L46), you have this thing here:

    expect(result.list.lenth).toBe(expected.list.lenth);

This happens again on [line 85](https://github.com/jesusgm/deepmergefn/blob/cae1a39319abbb67aba291ff0bb1f5a7e0ddc901/index.test.js#L85).

So you have passing tests but the tests are wrong. And _in this particular case_ it happens that the tests being wrong, hide an actual error in the code. If you do fix the tests to...

    expect(result.list.length).toBe(expected.list.length);

...you will notice that the tests don't pass because arrays are _not_ being merged correctly.

I would recommend not _just_ fixing those two lines in the tests, but actually using stricter assertions so that you not only compare the lengths, but also the actual content of the arrays.

----

Second:
Your approach to merging arrays is wrong (according to the tests, anyway) and it simply will not work.

Leaving aside the previous problem for a moment, what you're doing is:

 - you first `result[property] = obj1[property].map(...)`
 - then you  `result[property] = obj2[property].map(...)`

This will _never_ merge the two arrays into one. You'll only merge the _items_ (some of them) in the array, but you'll never get an array with _more_ elements than the original arrays.

----

Oh, sorry, one more:

According to your tests, merging these two arrays: `[1,2,3]` and `[3,4,5]` _should_ result in `[1,2,3,4,5]`. This means, I guess, that you're aiming to merge arrays on _unique_ values. That is, that the merged array will contain the *union* (in mathematical terms) of both arrays.

The problem is when you try to `deepMerge([{a:3}, {a:7}], [{a:7}, {b:3}])`. Again, your merging approach is wrong (as explained above), and you will get the weird result of `[{a:7},{a:7,b:3}]`.

So, when you fix the above problems, do remember to add another test for this too.

**Comment by jesusgm** [comment]
Thank you for reviewing the code and for your detailed comments.
I will review all the bugs you comment on and fix them as soon as I have a free time.

**Comment by jesusgm** [comment]
Fixed

**Comment by gezeta-id** [comment]
Well, I'm afraid you didn't really fix things.

You now have wildly different behaviours which make results surprisingly unexpected.

When you merge _two arrays_, you return the concatenation of both:

```javascript
deepMerge([1,2,3], [3,4,5]); 
// produces [1,2,3,3,4,5]
```

But when you merge objects with an array in a property, you just overwrite one with the other:

```javascript
deepMerge({ a: [1,2,3] } , { a: [3,4,5] }); 
// produces { a: [3,4,5] }
```

But then again, if the elements in the array are objects, you merge the items in some peculiar way:

```javascript
deepMerge({ a: [{b: 1} ,{ b: 2 } ] } , { a: [{b: 3}, {c: 4 }, {b: 5} ] });
// produces { a: [ {b:3}, {b:2,c:4}, {b:5} ] }
```

```javascript
deepMerge({ a: [{b: 1} ,{ b: 2 }, {b:7} ] } , { a: [{b: 3}, {c: 4 } ] });
// produces { a: [ {b:3}, {b:2,c:4} ] }
```

All these different ways of merging arrays depending on _where_ they are, or on what they contain, with the peculiarity of that last case where some elements may be merged while others may simply disappear because the second array is shorter, are rather surprising, even somewhat _random_ and, imo, make the whole thing useless.

What I find most surprising, though, is that you now you have a new test (`"Merges two object width complex array properties"`) which again is passing but is *wrong*, because you only check that "the items in `result` are in `expected`" but not that they are the same number of items. I mean, you could just return an empty array and it would pass the test every time.

**Comment by jesusgm** [comment]
I think now it is fixed.
Regarding arrays, I want the function to work as follows:
1.- If the elements are objects, they are mixed
2.- If the elements are not objects, we keep the last one
